from __future__ import annotations
import re
from api.schemas import Meal, NutritionTargets, ValidationInfo, DailyTotals, DayPlan
from typing import Any, Dict, List, Optional, Tuple

CALORIE_TOLERANCE = 0.20
MACRO_TOLERANCE = 0.35 # 35% variance allowed for daily macro totals to prevent rate-limiting retry loops

ALLERGEN_SYNONYMS = {
    "peanut": ["peanut", "peanuts", "groundnut", "groundnuts", "arachis"],
    "nut": ["nut", "nuts", "walnut", "almond", "cashew", "pecan", "pistachio", "macadamia", "hazelnut"],
    "dairy": ["dairy", "milk", "cheese", "butter", "yogurt", "cream", "whey", "casein", "ghee"],
    "egg": ["egg", "eggs", "albumen", "mayo", "mayonnaise"],
    "soy": ["soy", "soya", "soybean", "edamame", "tofu", "tempeh", "miso", "shoyu"],
    "wheat": ["wheat", "gluten", "flour", "bread", "pasta", "seitan", "semolina", "spelt", "bulgur"],
    "shellfish": ["shellfish", "shrimp", "prawn", "crab", "lobster", "crawfish", "mussel", "oyster", "scallop"],
    "fish": ["fish", "salmon", "tuna", "cod", "tilapia", "anchovy", "sardine"],
    "vegan": ["milk", "cheese", "yogurt", "butter", "ghee", "cream", "dahi", "egg", "eggs", "chicken", "beef", "mutton", "fish", "meat", "honey", "pork"],
    "vegetarian": ["chicken", "beef", "mutton", "fish", "meat", "pork"],
    "halal": ["pork", "bacon", "ham", "swine", "alcohol", "wine", "beer"],
    "gluten": ["wheat", "atta", "roti", "naan", "barley", "rye", "bread"],
    "beef": ["beef", "cow", "veal"],
    "pork": ["pork", "bacon", "ham", "swine"]
}

def get_synonyms(restriction: str) -> List[str]:
    """Returns the normalized list of synonyms for a given restriction."""
    r = restriction.lower().strip()
    # Check if the restriction matches any of our synonym groups
    for key, syns in ALLERGEN_SYNONYMS.items():
        if r == key or r in syns:
            return syns
    return [r]

def validate_meals(
    meals: List[Meal],
    targets: NutritionTargets,
    restrictions: List[str],
    disallowed_ingredients: Optional[List[str]] = None,
) -> Tuple[bool, List[str]]:
    """Validates the flat list of meals generated by the LLM."""
    errors = []
    disallowed_patterns = [
        (term, re.compile(rf"\b{re.escape(term.lower())}\b"))
        for term in (disallowed_ingredients or [])
    ]
    
    if len(meals) not in (21, 28):
        errors.append(f"Expected 21 to 28 meals, but got {len(meals)}.")
        
    # Group by day
    days = {}
    for m in meals:
        days.setdefault(m.day, []).append(m)
        
    if len(days) != 7:
        errors.append(f"Expected exactly 7 days of meals, got {len(days)}.")
        
    for day_label, day_meals in days.items():
        if len(day_meals) not in (3, 4):
            errors.append(f"{day_label} has {len(day_meals)} meals, expected 3 or 4 (Breakfast, Lunch, Snack, Dinner).")
            
        day_cals = sum(m.calories for m in day_meals)
        day_protein = sum(m.protein for m in day_meals)
        day_carbs = sum(m.carbs for m in day_meals)
        day_fat = sum(m.fat for m in day_meals)
        
        target_cals = targets.target_calories
        target_protein = getattr(targets, 'protein_g', 0)
        target_carbs = getattr(targets, 'carbs_g', 0)
        target_fat = getattr(targets, 'fat_g', 0)
        
        if abs(day_cals - target_cals) / target_cals > CALORIE_TOLERANCE:
            errors.append(f"{day_label} calories ({day_cals} kcal) is outside 20% tolerance of target ({target_cals} kcal).")
            
        if target_protein > 0 and abs(day_protein - target_protein) / target_protein > MACRO_TOLERANCE:
            errors.append(f"{day_label} protein ({day_protein}g) is outside 35% tolerance of target ({target_protein}g).")
            
        if target_carbs > 0 and abs(day_carbs - target_carbs) / target_carbs > MACRO_TOLERANCE:
            errors.append(f"{day_label} carbs ({day_carbs}g) is outside 35% tolerance of target ({target_carbs}g).")
            
        if target_fat > 0 and abs(day_fat - target_fat) / target_fat > MACRO_TOLERANCE:
            errors.append(f"{day_label} fat ({day_fat}g) is outside 35% tolerance of target ({target_fat}g).")
            
        # Check macro arithmetic for each meal
        for m in day_meals:
            if m.calories < 0 or m.protein < 0 or m.carbs < 0 or m.fat < 0:
                errors.append(f"Negative nutrition values found in {m.name} on {day_label}.")
            
            calc_cals = m.protein * 4 + m.carbs * 4 + m.fat * 9
            if abs(calc_cals - m.calories) > (m.calories * 0.25 + 30):
                errors.append(f"Macros for '{m.name}' don't add up correctly to its calories ({calc_cals} kcal vs {m.calories} kcal).")
                
            # Check explicit restrictions using word boundaries and synonyms
            name_lower = m.name.lower()
            ingredients_lower = [ing.lower() for ing in getattr(m, 'ingredients', [])]
            for r in restrictions:
                syns = get_synonyms(r)
                for syn in syns:
                    pattern = re.compile(rf'\b{re.escape(syn)}\b')
                    if pattern.search(name_lower):
                        errors.append(f"Meal '{m.name}' violates explicit restriction '{r}' (matched '{syn}').")
                    elif any(pattern.search(ing) for ing in ingredients_lower):
                        errors.append(f"Meal '{m.name}' contains prohibited ingredient matching restriction '{r}' (matched '{syn}').")

            for term, pattern in disallowed_patterns:
                if pattern.search(name_lower) or any(pattern.search(ing) for ing in ingredients_lower):
                    errors.append(f"Meal '{m.name}' uses '{term}', which is not a common everyday ingredient in the selected region.")
                    
    return len(errors) == 0, errors

def structure_day_plans(meals: List[Meal], forecast: List[Dict[str, Any]]) -> List[DayPlan]:
    """Converts the flat list of meals into the structured DayPlan list."""
    # Group by day
    days_dict = {}
    for m in meals:
        days_dict.setdefault(m.day, []).append(m)
        
    day_plans = []
    for i, (day_label, day_meals) in enumerate(days_dict.items()):
        day_cals = sum(m.calories for m in day_meals)
        day_protein = sum(m.protein for m in day_meals)
        day_carbs = sum(m.carbs for m in day_meals)
        day_fat = sum(m.fat for m in day_meals)
        
        weather_data = forecast[i] if i < len(forecast) else None
        date_str = weather_data.get("time", f"Day {i+1}") if weather_data else f"Day {i+1}"
        
        day_plans.append(DayPlan(
            date=date_str,
            day_label=day_label,
            weather=weather_data,
            meals=day_meals,
            daily_totals=DailyTotals(
                calories=day_cals,
                protein_g=day_protein,
                carbs_g=day_carbs,
                fat_g=day_fat
            ),
            validation=ValidationInfo(valid=True, messages=["Passed deterministic checks"])
        ))
    return day_plans
